[package]
name = "cross_platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itoa = "1.0.4"
heapless = { workspace = true }
enum_dispatch = "0.3.11"
