[package]
name = "Julia_AVR_Rust"
version = "0.1.0"
authors = ["Flavio Vilante <https://twitter.com/FlavioVilante>"]
edition = '2018'

[dependencies]
avr-std-stub = "1.0.3"
ruduino = {  git = "https://github.com/avr-rust/ruduino", rev = "c057499" }

[profile.release]
lto = true
